src/accounts/urls.py
from django.urls import path, include
from . import views


app_name = "accounts"
urlpatterns = [
    # Automatic authentication URLs
    path("", include("django.contrib.auth.urls")),
    # Registration page
    path("register/", views.register, name="register"),
]

src/artworks/urls.py
from django.urls import path
from . import views

app_name = "artworks"
urlpatterns = [
    # mainpage
    path("", views.index, name="index"),
    # artworks list
    path("artworks/", views.artworks, name="artworks"),
    # new artwork
    path("new_artwork/", views.new_artwork, name="new_artwork"),
    # editing an artwork
    path("edit/<int:pk>/", views.edit_artwork, name="edit_artwork"),
    # deleting an artwork
    path("delete/<int:pk>/", views.delete_artwork, name="delete_artwork"),
    # artwork details
    path("<int:pk>/", views.artwork_details, name="artwork_detail"),
]

src/books/urls.py
from django.urls import path
from . import views

app_name = "books"
urlpatterns = [
    # books list
    path("", views.books, name="books"),
    # new book
    path("new_book/", views.new_book, name="new_book"),
    # editing a book
    path("edit/<int:pk>/", views.edit_book, name="edit_book"),
    # deleting a book
    path("delete/<int:pk>/", views.delete_book, name="delete_book"),
    # book details
    path("<int:pk>/", views.book_details, name="book_details"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.resolvers import settings
from django.conf.urls.static import static

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("artworks.urls"),
    ),
    path(
        "accounts/",
        include("accounts.urls"),
    ),
    path(
        "books/",
        include("books.urls"),
    ),
    path(
        "movies/",
        include("movies.urls"),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/movies/urls.py
from django.urls import path
from . import views

app_name = "movies"
urlpatterns = [
    # movies list
    path("", views.movies, name="movies"),
    # new movie
    path("new_movie/", views.new_movie, name="new_movie"),
    # edit a movie
    path("edit/<int:pk>/", views.edit_movie, name="edit_movie"),
    # delete a movie
    path("delete/<int:pk>/", views.delete_movie, name="delete_movie"),
    # movie details
    path("<int:pk>/", views.movie_details, name="movie_details"),
]

src/artworks/models.py
from django.db import models
from django.contrib.auth.models import User


class Artwork(models.Model):
    """Model of an artwork"""

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="artworks",
        help_text="owner",
    )

    title = models.CharField(
        max_length=200,
        verbose_name="Title",
        # help_text="title",
    )

    artist = models.CharField(
        null=True,
        blank=True,
        max_length=100,
        verbose_name="Artist",
        # help_text="artist",
    )

    year = models.IntegerField(
        null=True,
        blank=True,
        verbose_name="Year",
        # help_text="year",
    )

    medium = models.CharField(
        max_length=200,
        verbose_name="Medium",
        # help_text="medium",
    )

    dimensions = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="Size",
        # help_text="size",
    )

    discription = models.TextField(
        blank=True,
        verbose_name="discription",
        # help_text="additional discription",
    )

    image = models.ImageField(
        upload_to="artworks/%Y/%m/",
        null=True,
        blank=True,
        verbose_name="image",
        # help_text="artwork image",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="creation date",
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="last edited",
    )

    class Meta:
        verbose_name = "Artwork"
        verbose_name_plural = "Artworks"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} - {self.artist}"

src/artworks/forms.py
from django import forms
from .models import Artwork


class ArtworkForm(forms.ModelForm):
    class Meta:
        model = Artwork
        fields = [
            "title",
            "artist",
            "medium",
            "year",
            "dimensions",
            "image",
            "discription",
        ]

src/artworks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Artwork
from .forms import ArtworkForm


def index(request):
    return render(request, "artworks/index.html")


@login_required
def artworks(request):
    artworks = Artwork.objects.filter(owner=request.user).order_by("created_at")
    context = {"artworks": artworks}
    return render(request, "artworks/artworks.html", context)


@login_required
def artwork_details(request, pk):
    artwork = get_object_or_404(Artwork, pk=pk, owner=request.user)
    context = {"artwork": artwork}
    return render(request, "artworks/artwork_details.html", context)


@login_required
def new_artwork(request):
    "Add new artwork"
    if request.method != "POST":
        # If empty creating a new form
        form = ArtworkForm()
    else:
        # Else filling a form with POSTed data
        form = ArtworkForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            artwork = form.save(commit=False)
            artwork.owner = request.user
            artwork.save()
            return redirect("artworks:artworks")

    # Wyświetlanie pustego formularza
    context = {"form": form}
    print("USER:", request.user, request.user.is_authenticated)
    return render(request, "artworks/new_artwork.html", context)


@login_required
def edit_artwork(request, pk):
    """Edit an artwork"""
    artwork = get_object_or_404(Artwork, pk=pk, owner=request.user)
    if request.method != "POST":
        form = ArtworkForm(instance=artwork)
    else:
        form = ArtworkForm(instance=artwork, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Artwork updated successfully!")
            return redirect("artworks:artworks")
    context = {"form": form, "artwork": artwork}
    return render(request, "artworks/edit_artwork.html", context)


@login_required
def delete_artwork(request, pk):
    artwork = get_object_or_404(Artwork, pk=pk)
    if request.method == "POST":
        artwork.delete()
        messages.success(request, "artwork deleted successfully!")
        return redirect("artworks:artworks")
    context = {"artworks": artworks}
    return render(request, "artworks/artworks.html", context)

src/artworks/templates/artworks/artwork_detail.html
{% extends "artworks/base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="containter mt-4">
        <div class="row">
            <div class="col-md-6">
                {% if artwork.image %}
                    <img src="{{ artwork.image.url }}"
                         alt="{{ artwork.title }}"
                         class="img-fluid shadow"
                         style="width: 100%;
                                max-height: 600px;
                                object-fit: contain">
                {% else %}
                    <div class="alert alert-secondary text-center">
                        <p>No image available</p>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6">
                <h2>{{ artwork.title }}</h2>
                <table class="table-borderless">
                    <tr>
                        <th>Artist:</th>
                        <td>{{ artwork.artist }}</td>
                    </tr>
                    <tr>
                        <th>Year:</th>
                        <td>{{ artwork.year }}</td>
                    </tr>
                    <tr>
                        <th>Medium:</th>
                        <td>{{ artwork.medium }}</td>
                    </tr>
                    <tr>
                        <th>Dimensions:</th>
                        <td>{{ artwork.dimensions }}</td>
                    </tr>
                    <tr>
                        <th>Created:</th>
                        <td>{{ artwork.created_at|date:"d.m.Y H:i" }}</td>
                    </tr>
                    <tr>
                        <th>Last updated:</th>
                        <td>{{ artwork.updated_at|date:"d.m.Y H:i" }}</td>
                    </tr>
                </table>
                <div class="mt-4">
                    <a href="{% url 'artworks:edit_artwork' artwork.pk %}"
                       class="btn btn-outline-dark">edit</a>
                    <form method="post"
                          action="{% url 'artworks:delete_artwork' artwork.pk %}"
                          style="display: inline"
                          onsubmit="return confirm('are you sure you want to delete {{ artwork.title }}?');">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-dark ">delete</button>
                    </form>
                </div>
            </div>
            <div class="containter mt-4">
                {% if artwork.discription %}
                    <table class="table-borderless">
                        <tr>
                            <th>Discription:</th>
                            <td>{{ artwork.discription }}</td>
                        </tr>
                    </table>
                {% endif %}
            </div>
        {% endblock content %}

src/artworks/templates/artworks/artwork_details.html
{% extends "artworks/base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="containter mt-4">
        <div class="row">
            <div class="col-md-6">
                {% if artwork.image %}
                    <img src="{{ artwork.image.url }}"
                         alt="{{ artwork.title }}"
                         class="img-fluid shadow"
                         style="width: 100%;
                                max-height: 600px;
                                object-fit: contain">
                {% else %}
                    <div class="alert alert-secondary text-container"
                         style="text-align: center;
                                background-color: white">
                        <p>No image available</p>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6">
                <h2>{{ artwork.title }}</h2>
                <table class="table-borderless">
                    <tr>
                        <th class="pe-3">Artist:</th>
                        <td>{{ artwork.artist }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Year:</th>
                        <td>{{ artwork.year }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Medium:</th>
                        <td>{{ artwork.medium }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Dimensions:</th>
                        <td>{{ artwork.dimensions }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Created:</th>
                        <td>{{ artwork.created_at|date:"d.m.Y H:i" }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Last updated:</th>
                        <td>{{ artwork.updated_at|date:"d.m.Y H:i" }}</td>
                    </tr>
                </table>
                <div class="mt-4">
                    <a href="{% url 'artworks:edit_artwork' artwork.pk %}" class="btn "><i class="bi bi-pencil-fill"></i></a>
                    <form method="post"
                          action="{% url 'artworks:delete_artwork' artwork.pk %}"
                          style="display: inline"
                          onclick="event.stoppropagation()"
                          onsubmit="return confirm('are you sure you want to delete {{ artwork.title }}?');">
                        {% csrf_token %}
                        <button type="submit" class="btn">
                            <i class="bi bi-trash-fill"></i>
                        </button>
                    </form>
                </div>
            </div>
            {% if artwork.discription %}
                <div class="mt-4">
                    <table class="table-borderless">
                        <tr>
                            <thead>
                                <th>Discription:</th>
                            </thead>
                            <tbody>
                                <td>{{ artwork.discription }}</td>
                            </tbody>
                        </tr>
                    </table>
                </div>
            {% endif %}
        {% endblock content %}

src/artworks/templates/artworks/artworks.html
{% extends "artworks/base.html" %}}
{% block content %}
    <!-- <p>Artworks:</p> -->
    <!-- <button type="button" class="btn">Base class</button> -->
    <div class="d-flex justify-content-end">
        <a href="{% url "artworks:new_artwork" %}"
           class="btn"
           style="font-size: 2rem"><i class="bi bi-plus"></i></a>
    </div>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Artist</th>
                    <th>Medium</th>
                    <th>Dimensions</th>
                    <th>Year</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for artwork in artworks %}
                    <tr style="cursor: pointer"
                        onclick="window.location='{% url 'artworks:artwork_detail' artwork.pk %}';">
                        <td>
                            {% if artwork.image %}
                                <img src="{{ artwork.image.url }}"
                                     alt="{{ artwork.title }}"
                                     style="max-height:120px;
                                            object-fit:cover;
                                            display: block;
                                            margin-left: auto;
                                            margin-right: auto">
                            {% else %}
                                no image
                            {% endif %}
                        </td>
                        <td>{{ artwork.title }}</td>
                        <td>{{ artwork.artist }}</td>
                        <td>{{ artwork.medium }}</td>
                        <td>{{ artwork.dimensions }}</td>
                        <td>{{ artwork.year }}</td>
                        <td>
                            <a href="{% url 'artworks:edit_artwork' artwork.pk %}" class="btn "><i class="bi bi-pencil-fill"></i></a>
                            <form method="post"
                                  action="{% url 'artworks:delete_artwork' artwork.pk %}"
                                  style="display: inline"
                                  onsubmit="return confirm('are you sure you want to delete {{ artwork.title }}?');">
                                {% csrf_token %}
                                <button type="submit" class="btn" onclick="event.stopPropagation()">
                                    <i class="bi bi-trash-fill"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

src/artworks/templates/artworks/base.html
<!DOCTYPE html>
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Sakuhin</title>
        {% load static %}
        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <!--  CSS -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>
    <body class="{% block body_class %}{% endblock %}">
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'artworks:index' %}">作品</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse"
                        aria-controls="navbarCollapse"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'artworks:artworks' %}">Artworks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'books:books' %}">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'movies:movies' %}">Movies</a>
                        </li>
                    </ul>
                    <!-- Account related links -->
                    <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <span class="navbar-text me-2">Hello, {{ user.username }}.</span>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                            </li>
                        {% endif %}
                    </ul>
                    <!-- End of account related links -->
                    {% if user.is_authenticated %}
                        <form action="{% url 'accounts:logout' %}" method='post'>
                            {% csrf_token %}
                            <button name='submit' class='btn'>
                            Logout</i>
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
    </nav>
    <main class="container">
        <!-- <div class="pb-2 mb-2 border-bottom"> -->
        {% block page_header %}
        {% endblock page_header %}
    </div>
    <div class="container py-4 px-3 px-md-4 px-lg-5">
        {% block content %}
        {% endblock content %}
    </div>
</main>
</body>
</html>

src/artworks/templates/artworks/edit_artwork.html
{% extends "artworks/base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="d-flex justify-content-center">
        <h3>Edit: {{ artwork.title }}</h3>
    </div>
    <div class="d-flex justify-content-center">
        <form action="{% url "artworks:edit_artwork" artwork.pk %}"
              method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-flex justify-content-center gap-5">
                <button type="submit" class="btn btn-outline-dark">Save changes</button>
                <a href="{% url 'artworks:artworks' %}" class="btn btn-outline-dark">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

src/artworks/templates/artworks/index.html
{% extends "artworks/base.html" %}
{% load static %}
{% block body_class %}bg-hero{% endblock %}
{% block content %}
    <!-- Hero full screen -->
    <div class="d-flex justify-content-center align-items-center text-white"
         style="min-height: 100vh">
        <div class="text-center">
            <h1 class="display-3"></h1>
        </div>
    </div>
{% endblock %}

src/artworks/templates/artworks/new_artwork.html
{% extends "artworks/base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="d-flex justify-content-center">
        <a>Add a new Artwork:</a>
    </div>
    <div class="d-flex justify-content-center">
        <form action="{% url "artworks:new_artwork" %}"
              method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-outline-dark">Add the Artwork</button>
        </form>
    </div>
{% endblock content %}