src/artworks/urls.py
from django.urls import path
from . import views

app_name = "artworks"
urlpatterns = [
    # mainpage
    path("", views.index, name="index"),
    # artworks list
    path("artworks/", views.artworks, name="artworks"),
    # new artwork
    path("new_artwork/", views.new_artwork, name="new_artwork"),
    # editing an artwork
    path("edit/<int:pk>/", views.edit_artwork, name="edit_artwork"),
    # deleting an artwork
    path("delete/<int:pk>/", views.delete_artwork, name="delete_artwork"),
    # artwork details
    path("<int:pk>/", views.artwork_details, name="artwork_detail"),
]

src/books/urls.py
from django.urls import path
from . import views

app_name = "books"
urlpatterns = [
    # books list
    path("", views.books, name="books"),
    # new book
    path("new_book/", views.new_book, name="new_book"),
    # editing a book
    path("edit/<int:pk>/", views.edit_book, name="edit_book"),
    # deleting a book
    path("delete/<int:pk>/", views.delete_book, name="delete_book"),
    # book details
    path("<int:pk>/", views.book_details, name="book_details"),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.resolvers import settings
from django.conf.urls.static import static

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("artworks.urls"),
    ),
    path(
        "accounts/",
        include("accounts.urls"),
    ),
    path(
        "books/",
        include("books.urls"),
    ),
    path(
        "movies/",
        include("movies.urls"),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/books/models.py
from django.db import models
from django.contrib.auth.models import User


class Book(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="books")
    title = models.CharField(max_length=200, verbose_name="Title")
    author = models.CharField(max_length=100, blank=True, verbose_name="Author")
    year = models.IntegerField(null=True, blank=True, verbose_name="Year")
    isbn = models.CharField(max_length=13, blank=True, verbose_name="ISBN")
    publisher = models.CharField(max_length=100, blank=True, verbose_name="Publisher")
    pages = models.IntegerField(null=True, blank=True, verbose_name="Pages")
    cover = models.ImageField(upload_to="books/%Y/%m/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Book"
        verbose_name_plural = "Books"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} - {self.author}"

src/books/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            "title",
            "author",
            "year",
            "isbn",
            "publisher",
            "pages",
            "cover",
        ]

src/books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Book
from .forms import BookForm


@login_required
def books(request):
    books = Book.objects.filter(owner=request.user).order_by("created_at")
    context = {"books": books}
    return render(request, "books/books.html", context)


@login_required
def book_details(request, pk):
    """Display book details"""
    book = get_object_or_404(Book, pk=pk, owner=request.user)
    context = {"book": book}
    return render(request, "books/book_details.html", context)


@login_required
def new_book(request):
    "Add new book"
    if request.method != "POST":
        # If empty creating a new form
        form = BookForm()
    else:
        # Else filling a form with POSTed data
        form = BookForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.owner = request.user
            book.save()
            return redirect("books:books")

    # Wyświetlanie pustego formularza
    context = {"form": form}
    print("USER:", request.user, request.user.is_authenticated)
    return render(request, "books/new_book.html", context)


@login_required
def edit_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method != "POST":
        form = BookForm(instance=book)
    else:
        form = BookForm(instance=book, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Book updated successfully!")
            return redirect("artworks:artworks")
    context = {"form": form, "book": book}
    return render(request, "books/edit_book.html", context)


@login_required
def delete_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        book.delete()
        messages.success(request, "Book deleted successfully!")
        return redirect("books:books")
    context = {"books": books}
    return render(request, "books/books.html", context)

src/books/templates/books/book_details.html
{% extends "artworks/base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col mt-6">
                {% if book.cover %}
                    <img src="{{ book.cover.url }}"
                         alt="{{ book.title }}"
                         class="img-fluid shadow"
                         style="width: 100%;
                                max-height: 600px;
                                object-fit: contain">
                {% else %}
                    <div class="alert alert-secondary text-container"
                         style="text-align: center;
                                background-color: white">
                        <p>No cover available</p>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6">
                <h2>{{ book.title }}</h2>
                <table class="table-borderless">
                    <tr>
                        <th class="pe-3">Author</th>
                        <td>{{ book.author }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Year</th>
                        <td>{{ book.year }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">ISBN</th>
                        <td>{{ book.isbn }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Publisher</th>
                        <td>{{ book.publisher }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Pages</th>
                        <td>{{ book.pages }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Created:</th>
                        <td>{{ book.created_at|date:"d.m.Y H:i" }}</td>
                    </tr>
                    <tr>
                        <th class="pe-3">Last updated:</th>
                        <td>{{ book.updated_at|date:"d.m.Y H:i" }}</td>
                    </tr>
                </table>
                <div class="mt-4">
                    <a href="{% url 'books:edit_book' book.pk %}" class="btn "><i class="bi bi-pencil-fill"></i></a>
                    <form method="post"
                          action="{% url 'books:delete_book' book.pk %}"
                          style="display: inline"
                          onclick="event.stoppropagation()"
                          onsubmit="return confirm('are you sure you want to delete {{ book.title }}?');">
                        {% csrf_token %}
                        <button type="submit" class="btn">
                            <i class="bi bi-trash-fill"></i>
                        </button>
                    </form>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/books/templates/books/books.html
{% extends "artworks/base.html" %}}
{% load django_bootstrap5 %}
{% block content %}
    <!-- <p>Artworks:</p> -->
    <!-- <button type="button" class="btn">Base class</button> -->
    <div class="d-flex justify-content-end">
        <a href="{% url "books:new_book" %}" class="btn" style="font-size: 2rem"><i class="bi bi-plus"></i></a>
    </div>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Publisher</th>
                    <th>Year</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                    <tr style="cursor: pointer"
                        onclick="window.location='{% url 'books:book_details' book.pk %}';">
                        <td>
                            {% if book.cover %}
                                <img src="{{ book.cover.url }}"
                                     alt="{{ book.title }}"
                                     style="max-height:120px;
                                            object-fit:cover;
                                            display: block;
                                            margin-left: auto;
                                            margin-right: auto">
                            {% else %}
                                no image
                            {% endif %}
                        </td>
                        <td>{{ book.title }}</td>
                        <td>{{ book.author }}</td>
                        <td>{{ book.publisher }}</td>
                        <td>{{ book.year }}</td>
                        <td>
                            <a href="{% url 'books:edit_book' book.pk %}" class="btn "><i class="bi bi-pencil-fill"></i></a>
                            <form method="post"
                                  action="{% url 'books:delete_book' book.pk %}"
                                  style="display: inline"
                                  onsubmit="return confirm('are you sure you want to delete {{ book.title }}?');">
                                {% csrf_token %}
                                <button type="submit" class="btn" onclick="event.stopPropagation()">
                                    <i class="bi bi-trash-fill"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

src/books/templates/books/edit_book.html
{% extends "artworks/base.html" %}}
{% load django_bootstrap5 %}
{% block content %}
    <div class = "d-flex justify-content-center">
        <h3>Edit: {{ book.title }}</h3>
    </div>
    <div class = "d-flex justify-content-center">
        <form action="{% url "books:edit_book" book.pk %}"
              method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-flex justify-content-center gap-5">
                <button type="submit" class="btn btn-outline-dark">Save changes</button>
                <a href="{% url 'artworks:artworks' %}" class="btn btn-outline-dark">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

src/books/templates/books/new_book.html
{% extends "artworks/base.html" %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="d-flex justify-content-center">
        <a>Add a new book:</a>
    </div>
    <div class="d-flex justify-content-center">
        <form action="{% url "books:new_book" %}"
              method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-outline-dark">Add the book</button>
        </form>
    </div>
{% endblock content %}